### ISSUE TITLE
phpとRubyの共存

### ISSUE THREAD

**Issue by AkagiCrafter** [AkagiCrafter/Onset#4]
依存関係が余計に増えて、「どどんとふ」より導入の敷居が高いと見受けられます。
BCDiceのPHP化 OR 現状処理のRuby処理への変更をするべきだと思います。

**Comment by AkagiCrafter** [comment]
これに関してはどうしようもなくなってきました。
PHPコードをRubyに書き換えられればいいものの、手間が大変すぎる。

**Comment by kiridaruma** [comment]
これに関しては、書き直すの面倒なんでこのままでいいかなと思います  
無理にそろえてもいいことありませんし...

**Comment by AkagiCrafter** [comment]
うーん...
特に打開策も無いですし、単純にPHPとRubyを入れれば済むという問題ではあるのでクローズします。
