### ISSUE TITLE
$this->dirへの値の代入が出来ていない

### ISSUE THREAD

**Issue by AkagiCrafter** [AkagiCrafter/Onset#8]
`branch: Class` : `OnsetUtilities.php` : `32`
```php
$this->dir        = OnsetConfigure::ROOMSAVEPATH;
```

`branch: Class` : `test.php` : `51, 52`
```php
$deleteRoomInstance = new deleteRoom($roomName, $roomPassword, $rM);
echo $deleteRoomInstance->getVar();
```
これらのコードが実行された際、 **$this->dirはNULLになる** 。
挙動が全く訳がわからないので解決が現状不可能。

誰か、助けを...!

**Comment by kiridaruma** [comment]
deleteRoomクラスのコンストラクタで親クラス(OnsetUti...?)のコンストラクタ呼び出してないですね    
‘parent::__construct()‘  
をしてあげればいいと思います

**Comment by AkagiCrafter** [comment]
ありがとうございます! 解決したようです!
